# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -c release --arch arm64 --arch x86_64
    - name: Check path
      run: ls -la .build/apple/Products/Release
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: reading-time-macos
        path: .build/apple/Products/Release/Vapor_WebSocket_Test
        retention-days: 1
